name: chat
description: Frontend for chat app
version: 0.0.2
environment:
  sdk: '>=2.0.0-dev.64.2 <3.0.0'
dependencies:
  logging: ^0.11.3+2
dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3+4
  build_web_compilers: ^0.4.4+3
  test: ^1.0.0
  mockito: ^3.0.0
  analyzer: ^0.32.6
  front_end: ^0.1.4+2
  kernel: ^0.3.4+2
