name: chat
description: Frontend for chat app
version: 0.0.2
environment:
  sdk: '>=2.0.0-dev.64.2 <3.0.0'
dependencies:
  logging: ^0.11.3+2
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
