name: chat
description: Frontend for chat app
version: 0.0.2
environment:
  sdk: '>=2.4.0 < 3.0.0'
dependencies:
  logging: ^0.11.3+2
dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3+4
  build_web_compilers: ^2.8.0
  test: ^1.0.0
  mockito: ^4.1.1
  #analyzer: ^0.39.4
  front_end: ^0.1.29
  #kernel: ^0.3.29
