name: gritter
description: dart test
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.18
  mockito: ^1.0.1
transformers:
- dart_to_js_script_rewriter
