name: chat_go
description: dart test
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  dart_to_js_script_rewriter: ^1.0.2
  test: ^0.12.20+10
  mockito: ^2.0.2
  logging: ^0.11.3+1
transformers:
- dart_to_js_script_rewriter
